# Site settings
author: Adam Weissman
title: <p style="color:red">Thor's Hammer</p>
header-img: img/home-bg.png
email: adam@comedytragedyepic.com
copyright_name: Adam Weissman
description: > # this means to ignore newlines until "baseurl:"
  Smash Problems.  Work with Dust.  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AdamWeissman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
